#!/bin/bash
export XDG_RUNTIME_DIR=/run/user/1000

ip=`echo $SSH_CONNECTION | cut -d " " -f 1`

logger -t ssh-wrapper $USER login from $ip
notify-send "User $USER just logged in from $ip" --urgency=critical
