#!/usr/bin/env bash

if [ $XDG_SESSION_TYPE = "x11" ]; then
  color=$(gpick -so)
  echo $color | xclip -selection clipboard
  notification "Colorpicker" "$color"
elif [ $XDG_SESSION_TYPE = "wayland" ]; then
  color=$(hyprpicker -nf hex)
  wl-copy $color
  notification "Colorpicker" "$color"
fi
