#!/bin/bash

function handle {
  # openwindow>>62129a69fd70,1,Alacritty,Alacritty
  if [[ ${1:0:10} == "openwindow" ]]; then
    hyprctl dispatch movewindowpixel "exact $((RANDOM%3098)) $((RANDOM%1248)),address:0x${1:12:12}"
  fi
}

socat - "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
