#!/usr/bin/python
import matplotlib.pyplot as plt
file = open('e-speed', 'r')
data_seconds = list(map(int, file.read().split('\n')[:-1]))
file.close()
plt.title(f'Avr. = {sum(data_seconds)/len(data_seconds)}sec')
plt.plot(data_seconds)
plt.show()
