#!/usr/bin/env bash

/usr/bin/telegram-desktop &
/usr/bin/easyeffects &
/usr/bin/alacritty --class "BpyTOP" -e "bpytop"
sleep 2
/usr/bin/alacritty msg create-window --class "pulsemixer" -e "pulsemixer"
/usr/bin/alacritty msg create-window --class "nvtop" -e "nvtop"

