#!/usr/bin/env bash

/usr/bin/alacritty --class "btm" -e "btm" &
sleep 2
/usr/bin/alacritty msg create-window --class "nvtop" -e "nvtop"
/usr/bin/alacritty msg create-window --class "pulsemixer" -e "pulsemixer"
/usr/bin/easyeffects &
/usr/bin/telegram-desktop &
