#!/bin/bash

updates="$(cat /home/obey/.bins/pending_updates)"
if [ "$updates" == "" ]; then
    number="0"
else
    number="$(echo "$updates" | wc -l)"
fi

if [ $number != "0" ]; then
    if [ "$number" -gt "10" ]; then
        more=$(expr $number - 10)
        updates=$(echo "$updates" | head)
        /home/obey/.bins/notification "There are updates for:" "$updates\nand $more more..." "critical"
    else
        /home/obey/.bins/notification "There are updates for:" "$updates" "critical"
    fi
fi
