[colors.primary]
background = "#{background.strip}"
foreground = "#{foreground.strip}"

[colors.bright]
black   = "#{color0.strip}"
blue    = "#{color1.strip}"
cyan    = "#{color2.strip}"
green   = "#{color3.strip}"
magenta = "#{color4.strip}"
red     = "#{color5.strip}"
white   = "#{color6.strip}"
yellow  = "#{color7.strip}"

[colors.cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.footer_bar]
background = "#{foreground.strip}"
foreground = "#{background.strip}"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black   = "#{color0.strip}"
blue    = "#{color1.strip}"
cyan    = "#{color2.strip}"
green   = "#{color3.strip}"
magenta = "#{color4.strip}"
red     = "#{color5.strip}"
white   = "#{color6.strip}"
yellow  = "#{color7.strip}"

[colors.search.focused_match]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.matches]
background = "CellBackground"
foreground = "CellForeground"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"
